"""Export the pinned ONNX Model Zoo MNIST CNN; no training or random weights."""
from pathlib import Path
import argparse
import gzip
import hashlib
import json
import numpy as np
import onnx
from onnx import numpy_helper
import onnxruntime as ort

ROOT = Path(__file__).resolve().parents[1]
SHA256 = '2f06e72de813a8635c9bc0397ac447a601bdbfa7df4bebc278723b958831c9bf'

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--data-dir', type=Path, required=True)
    a = p.parse_args()
    path = ROOT / 'model/mnist-8.onnx'
    assert hashlib.sha256(path.read_bytes()).hexdigest() == SHA256
    model = onnx.load(path)
    weights = {t.name: numpy_helper.to_array(t) for t in model.graph.initializer}
    mapping = [('conv1_w', 'Parameter5', (8, 1, 5, 5)),
               ('conv1_b', 'Parameter6', (8, 1, 1)),
               ('conv2_w', 'Parameter87', (16, 8, 5, 5)),
               ('conv2_b', 'Parameter88', (16, 1, 1)),
               ('dense_w', 'Parameter193', (16, 4, 4, 10)),
               ('dense_b', 'Parameter194', (1, 10))]
    lines = ['/* Generated by tools/export_model.py. Model Zoo MNIST, MIT license.',
             ' * Source SHA256: ' + SHA256 + ' */', '#pragma once', '#include <stdint.h>']
    for name, source, shape in mapping:
        w = weights[source]
        assert w.shape == shape
        lines.append(f'static const float {name}[{w.size}] = {{')
        # float.hex is exact, avoiding decimal exporter roundoff.
        values = [float(v).hex() + 'f' for v in w.flat]
        lines += [','.join(values[i:i+8]) + ',' for i in range(0, len(values), 8)]
        lines.append('};')
    (ROOT / 'main/model_weights.h').write_text('\n'.join(lines) + '\n', encoding='utf-8')

    x = np.frombuffer(gzip.decompress((a.data_dir / 't10k-images-idx3-ubyte.gz').read_bytes()),
                      dtype=np.uint8, offset=16).reshape(-1, 28, 28)
    y = np.frombuffer(gzip.decompress((a.data_dir / 't10k-labels-idx1-ubyte.gz').read_bytes()),
                      dtype=np.uint8, offset=8)
    options = ort.SessionOptions()
    options.intra_op_num_threads = 1
    session = ort.InferenceSession(str(path), sess_options=options, providers=['CPUExecutionProvider'])
    samples, outputs, indices = [], [], []
    correct = 0
    for i, (img, label) in enumerate(zip(x, y)):
        logits = session.run(None, {'Input3': img.astype(np.float32)[None, None] / 255.0})[0][0]
        correct += int(logits.argmax() == label)
        if int(label) not in [int(y[j]) for j in indices] and logits.argmax() == label:
            indices.append(i)
            samples.append(img)
            outputs.append(logits)
    order = np.argsort(y[indices])
    samples = np.array(samples)[order]
    outputs = np.array(outputs)[order]
    indices = np.array(indices)[order]
    lines = ['/* Official MNIST held-out samples, used only for boot self-test. */',
             '#pragma once', '#include <stdint.h>',
             'static const uint8_t selftest_images[10][784] = {']
    for img in samples:
        lines.append('{' + ','.join(str(int(v)) for v in img.flat) + '},')
    lines += ['};', 'static const float selftest_logits[10][10] = {']
    for row in outputs:
        lines.append('{' + ','.join(float(v).hex() + 'f' for v in row) + '},')
    lines.append('};')
    (ROOT / 'main/model_selftest.h').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    report = dict(model_sha256=SHA256, weights=sum(weights[s].size for _,s,_ in mapping),
                  dtype='float32', test_count=len(y), correct=correct,
                  accuracy=correct / len(y), selftest_indices=indices.tolist())
    (ROOT / 'model/validation.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2))

if __name__ == '__main__':
    main()
